update=Wed 29 Nov 2017 06:15:25 PM -02
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=/home/arthur/Kicad Lib/kicad-library-master/library/ac-dc
LibName31=/home/arthur/Kicad Lib/kicad-library-master/library/adc-dac
LibName32=/home/arthur/Kicad Lib/kicad-library-master/library/Altera
LibName33=/home/arthur/Kicad Lib/kicad-library-master/library/analog_devices
LibName34=/home/arthur/Kicad Lib/kicad-library-master/library/analog_switches
LibName35=/home/arthur/Kicad Lib/kicad-library-master/library/atmel
LibName36=/home/arthur/Kicad Lib/kicad-library-master/library/audio
LibName37=/home/arthur/Kicad Lib/kicad-library-master/library/Battery_Management
LibName38=/home/arthur/Kicad Lib/kicad-library-master/library/bbd
LibName39=/home/arthur/Kicad Lib/kicad-library-master/library/Bosch
LibName40=/home/arthur/Kicad Lib/kicad-library-master/library/brooktre
LibName41=/home/arthur/Kicad Lib/kicad-library-master/library/Connector
LibName42=/home/arthur/Kicad Lib/kicad-library-master/library/contrib
LibName43=/home/arthur/Kicad Lib/kicad-library-master/library/cypress
LibName44=/home/arthur/Kicad Lib/kicad-library-master/library/dc-dc
LibName45=/home/arthur/Kicad Lib/kicad-library-master/library/device
LibName46=/home/arthur/Kicad Lib/kicad-library-master/library/digital-audio
LibName47=/home/arthur/Kicad Lib/kicad-library-master/library/Diode
LibName48=/home/arthur/Kicad Lib/kicad-library-master/library/Display
LibName49=/home/arthur/Kicad Lib/kicad-library-master/library/driver_gate
LibName50=/home/arthur/Kicad Lib/kicad-library-master/library/dsp
LibName51=/home/arthur/Kicad Lib/kicad-library-master/library/DSP_Microchip_DSPIC33
LibName52=/home/arthur/Kicad Lib/kicad-library-master/library/elec-unifil
LibName53=/home/arthur/Kicad Lib/kicad-library-master/library/ESD_Protection
LibName54=/home/arthur/Kicad Lib/kicad-library-master/library/Espressif
LibName55=/home/arthur/Kicad Lib/kicad-library-master/library/FPGA_Actel
LibName56=/home/arthur/Kicad Lib/kicad-library-master/library/ftdi
LibName57=/home/arthur/Kicad Lib/kicad-library-master/library/gennum
LibName58=/home/arthur/Kicad Lib/kicad-library-master/library/Graphic
LibName59=/home/arthur/Kicad Lib/kicad-library-master/library/hc11
LibName60=/home/arthur/Kicad Lib/kicad-library-master/library/infineon
LibName61=/home/arthur/Kicad Lib/kicad-library-master/library/intel
LibName62=/home/arthur/Kicad Lib/kicad-library-master/library/interface
LibName63=/home/arthur/Kicad Lib/kicad-library-master/library/intersil
LibName64=/home/arthur/Kicad Lib/kicad-library-master/library/ir
LibName65=/home/arthur/Kicad Lib/kicad-library-master/library/Lattice
LibName66=/home/arthur/Kicad Lib/kicad-library-master/library/LED
LibName67=/home/arthur/Kicad Lib/kicad-library-master/library/LEM
LibName68=/home/arthur/Kicad Lib/kicad-library-master/library/linear
LibName69=/home/arthur/Kicad Lib/kicad-library-master/library/Logic_74xgxx
LibName70=/home/arthur/Kicad Lib/kicad-library-master/library/Logic_74xx
LibName71=/home/arthur/Kicad Lib/kicad-library-master/library/Logic_CMOS_4000
LibName72=/home/arthur/Kicad Lib/kicad-library-master/library/Logic_CMOS_IEEE
LibName73=/home/arthur/Kicad Lib/kicad-library-master/library/logic_programmable
LibName74=/home/arthur/Kicad Lib/kicad-library-master/library/Logic_TTL_IEEE
LibName75=/home/arthur/Kicad Lib/kicad-library-master/library/maxim
LibName76=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC10
LibName77=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC12
LibName78=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC16
LibName79=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC18
LibName80=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC24
LibName81=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Microchip_PIC32
LibName82=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_NXP_Kinetis
LibName83=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_NXP_LPC
LibName84=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_NXP_S08
LibName85=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Parallax
LibName86=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_ST_STM8
LibName87=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_ST_STM32
LibName88=/home/arthur/Kicad Lib/kicad-library-master/library/MCU_Texas_MSP430
LibName89=/home/arthur/Kicad Lib/kicad-library-master/library/Mechanical
LibName90=/home/arthur/Kicad Lib/kicad-library-master/library/memory
LibName91=/home/arthur/Kicad Lib/kicad-library-master/library/microchip
LibName92=/home/arthur/Kicad Lib/kicad-library-master/library/microcontrollers
LibName93=/home/arthur/Kicad Lib/kicad-library-master/library/modules
LibName94=/home/arthur/Kicad Lib/kicad-library-master/library/Motor
LibName95=/home/arthur/Kicad Lib/kicad-library-master/library/motor_drivers
LibName96=/home/arthur/Kicad Lib/kicad-library-master/library/motorola
LibName97=/home/arthur/Kicad Lib/kicad-library-master/library/nordicsemi
LibName98=/home/arthur/Kicad Lib/kicad-library-master/library/nxp
LibName99=/home/arthur/Kicad Lib/kicad-library-master/library/onsemi
LibName100=/home/arthur/Kicad Lib/kicad-library-master/library/opto
LibName101=/home/arthur/Kicad Lib/kicad-library-master/library/Oscillators
LibName102=/home/arthur/Kicad Lib/kicad-library-master/library/philips
LibName103=/home/arthur/Kicad Lib/kicad-library-master/library/power
LibName104=/home/arthur/Kicad Lib/kicad-library-master/library/powerint
LibName105=/home/arthur/Kicad Lib/kicad-library-master/library/Power_Management
LibName106=/home/arthur/Kicad Lib/kicad-library-master/library/pspice
LibName107=/home/arthur/Kicad Lib/kicad-library-master/library/references
LibName108=/home/arthur/Kicad Lib/kicad-library-master/library/regul
LibName109=/home/arthur/Kicad Lib/kicad-library-master/library/Relay
LibName110=/home/arthur/Kicad Lib/kicad-library-master/library/rfcom
LibName111=/home/arthur/Kicad Lib/kicad-library-master/library/RFSolutions
LibName112=/home/arthur/Kicad Lib/kicad-library-master/library/Sensor_Current
LibName113=/home/arthur/Kicad Lib/kicad-library-master/library/sensors
LibName114=/home/arthur/Kicad Lib/kicad-library-master/library/silabs
LibName115=/home/arthur/Kicad Lib/kicad-library-master/library/siliconi
LibName116=/home/arthur/Kicad Lib/kicad-library-master/library/supertex
LibName117=/home/arthur/Kicad Lib/kicad-library-master/library/Switch
LibName118=/home/arthur/Kicad Lib/kicad-library-master/library/texas
LibName119=/home/arthur/Kicad Lib/kicad-library-master/library/Transformer
LibName120=/home/arthur/Kicad Lib/kicad-library-master/library/Transistor
LibName121=/home/arthur/Kicad Lib/kicad-library-master/library/triac_thyristor
LibName122=/home/arthur/Kicad Lib/kicad-library-master/library/Valve
LibName123=/home/arthur/Kicad Lib/kicad-library-master/library/video
LibName124=/home/arthur/Kicad Lib/kicad-library-master/library/wiznet
LibName125=/home/arthur/Kicad Lib/kicad-library-master/library/Worldsemi
LibName126=/home/arthur/Kicad Lib/kicad-library-master/library/Xicor
LibName127=/home/arthur/Kicad Lib/kicad-library-master/library/xilinx
LibName128=/home/arthur/Kicad Lib/kicad-library-master/library/zetex
LibName129=/home/arthur/Kicad Lib/kicad-library-master/library/Zilog
